package exceptions;


class Arithmetic
{
	public void division(int x, int y) throws ArithmeticException
	{
		int z = x / y;
		System.out.println(z);
	}	
}

public class ThrowsDemo {

	public static void main(String[] args) {
		
		try
		{
			new Arithmetic().division(2, 0);
		}
		catch (ArithmeticException e)
		{
			System.out.println("This is a user-defined exception! Exception: " + e.message());
		}
		
	}
	
}
