package exceptions;

import java.util.Scanner;

public class ExceptionDemo {

	public void message()
	{
		System.out.println("yo");
	}
	
	public static void main(String[] args) {
		
//		Scanner sc = new Scanner(System.in);
//		System.out.println("Please enter two integers: ");
//		int x = Integer.parseInt(sc.nextLine());
//		int y = Integer.parseInt(sc.nextLine());
//		try 
//		{
//			int z = x / y; // divide by 0 causes java.lang.ArithmeticException: / by zero
//			System.out.println("z = " + z);
//		}
//		catch (ArithmeticException e) // user-defined exception, catches the thrown object
//		{
//			System.out.println("This is a user-defined exception! ArithmeticException: " + e.getMessage());
//		}
//		System.out.println("Welcome!");
		
		String[] names = {"Chris", "Charles", "Koko", "Chelsea"};
		try
		{
			System.out.println(names[10]); // accessing 10th element causes java.lang.ArrayIndexOutOfBoundsException
		}
		catch (ArrayIndexOutOfBoundsException e)
		{
			System.out.println("This is a user-definde exception! ArrayIndexOutOfBoundsException: " + e.getMessage());
		}
		System.out.println("Welcome!");
		
//		ExceptionDemo demo = null;
//		demo.message(); // attempting to call a function from null causes java.lang.NullPointerException
		
	}
	
}
